### ISSUE TITLE
In Klee, allow materials to participate in shaping and replacement rules without geometric data

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#1104]
Our Klee format currently supports input geometry in `stl` and `c2c` format.

We have recently added support for importing initial volume fractions into the sample-based shaper, but these shapes cannot participate in the replacement rules, which might lead to invalid results. (See #1069).

I'd like to add the ability for shapes/materials to participate in shaping without an input geometry.

My proposal is to allow a format of `none` so users can explicitly order the input materials and tag them with replacement rules.

e.g. note the `geometry` section in the below example
```yaml
dimensions: 2
units: cm

shapes:
  - name: input_rock
    material: rock
    geometry:
      format: none  # <-- new, has a material name, but no (new) geometric data

  - name: input_paper
    material: paper
    geometry:
      format: none  # <-- new
    does_not_replace: [scissor]  # <-- `paper` material will replace everything, including `rock`, but not `scissor`
```

I discussed this w/ @wnissen on 5/30/2023.
