### ISSUE TITLE
Conflicting definition of IndexType

### ISSUE THREAD

**Issue by nselliott** [LLNL/axom#43]
In src/axom/core/Types.hpp we have:

```
 #if defined(AXOM_USE_64BIT_INDEXTYPE) && !defined(AXOM_NO_INT64_T)
 using IndexType = int64;
 #else
 using IndexType = int32;
 #endif
```

And in src/axom/sidre/core/SidreTypes.hpp we have:

```
 typedef SIDRE_IndexType IndexType;
```

SIDRE_IndexType is elsewhere defined as int64_t.  We should define IndexType in only one place.

**Comment by gzagaris** [comment]
I think this could be probably fixed by adding the ``cpp_if`` in the ``sidre_shroud.yaml`` (hopefully) or we need to do something like that. We are using that in quest for conditionally compiling routines that take an MPI communicator, but, I am not sure if we can use it out-of-the-box for types.

@ltaylor16 thoughts?

**Comment by kennyweiss** [comment]
Thanks @nselliott.

The problem is actually here: 
https://github.com/LLNL/axom/blob/7c1185420de47bbd4ccf466b9c5f1e38fd69891d/src/axom/sidre/core/SidreDataTypeIds.h#L23-L25

If we still need `SIDRE_IndexType`, I think it should be defined as follows:
```cpp
using SIDRE_IndexType = axom::IndexType;
```

Since `axom::IndexType` defaults to 32 bits, and this one redefines it to 64 bits, this definitely needs to be resolved.

**Comment by kennyweiss** [comment]
Here are the relevant lines in Sidre's shroud:
https://github.com/LLNL/axom/blob/7c1185420de47bbd4ccf466b9c5f1e38fd69891d/src/axom/sidre/interface/sidre_shroud.yaml#L30-L35

@ltaylor16 -- could this line be changed to support a configuration dependent type (e.g. `int32_t` or `int64_t`) based on `AXOM_USE_64BIT_INDEXTYPE`?

**Comment by gzagaris** [comment]
Hmm....I am surprised we are hardcoding `SIDRE_IndexType` ourselves. I thought that shroud ``shroud`` would emit its definition. I understand this was done a while ago, but, is there a reason ``shroud`` couldn't do this?

For example, based on how we do something similar in ``quest`` could we do something like this:
```
declarations:
   -decl: #define SIDRE_IndexType int64_t
     fields:
          c_header: axom/sidre/interface/SidreTypes.hpp
          cpp_if: ifdef AXOM_USE_64BIT_INDEXTYPE
   -decl: #define SIDRE_IndexType int32_t
     fields:
          c_header: axom/sidre/interface/SidreTypes.hpp
          cpp_if: ifndef AXOM_USE_64BIT_INDEXTYPE

```
