### ISSUE TITLE
Implement replacement rules for IntersectionShaper.

### ISSUE THREAD

**Issue by BradWhitlock** [LLNL/axom#981]
The IntersectionShaper class needs to implement the "replaces" and "does_not_replace" replacement rules that help govern how the material volume fractions are written into the fields produced by the shaper.

* Implement the rules
* Create datasets that show the rules work for revolved contours used by IntersectionShaper.
* Create CI tests

**Comment by BradWhitlock** [comment]
I'm prototyping replacement rules for the IntersectionShaper. I made a fairly simple set of contours that I'm using to build up layers of materials. I find that for some things, multiple passes/layers are needed to represent the shapes because the area under the curve from the function down to the axis of revolution get covered. This makes it harder to represent shapes that are not on that axis (you have to write their upper part and then their lower part and hope that you don't wipe out other things under them)

```
dimensions: 2

shapes:
- name: shape0
  material: mat0
  geometry:
    format: c2c
    path: ../contours/case1/outer.contour
- name: shape1
  material: mat1
  geometry:
    format: c2c
    path: ../contours/case1/uppercircle.contour
- name: shape2
  material: mat2
  does_not_replace: [mat0]
  geometry:
    format: c2c
    path: ../contours/case1/lowercircle.contour
- name: shape3
  material: mat3
  replaces: [mat0]
  geometry:
    format: c2c
    path: ../contours/case1/lowercircle.contour
- name: shape4
  material: mat4
  replaces: [mat1, mat3]
  geometry:
    format: c2c
    path: ../contours/case1/smallcircleupper.contour
- name: shape5
  material: mat5
  replaces: [mat0]
  geometry:
    format: c2c
    path: ../contours/case1/smallcircleupper.contour
- name: shape6
  material: mat6
  replaces: [mat2]
  geometry:
    format: c2c
    path: ../contours/case1/smallcircleupper.contour
- name: shape7
  material: mat2
  replaces: [mat6]
  geometry:
    format: c2c
    path: ../contours/case1/smallcirclelower.contour

```
![contour](https://user-images.githubusercontent.com/2072964/208530324-501db1d0-e0fe-4bad-9ee1-bbab0f0c125d.png)
